
global:
  security:
    allowInsecureImages: true

image:
  registry: docker.io
  repository: bitnamilegacy/kafka

listeners:
  client:
    protocol: PLAINTEXT
    containerPort: 9092
  controller:
    protocol: PLAINTEXT
    containerPort: 9093
  interbroker:
    protocol: PLAINTEXT
    containerPort: 9094
  external:
    protocol: PLAINTEXT
    containerPort: 9095

controller:
  replicaCount: 1
  controllerOnly: false
  persistence:
    enabled: true
    size: 8Gi
    storageClass: "standard"
  resourcesPreset: "small"

broker:
  replicaCount: 0

overrideConfiguration:
  auto.create.topics.enable: "true"
  offsets.topic.replication.factor: "1"
  transaction.state.log.replication.factor: "1"
  transaction.state.log.min.isr: "1"
